# Generated by Django 2.0.3 on 2018-03-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Son',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_site', models.CharField(choices=[('youtube', 'youtube'), ('soundcloud', 'soundcloud'), ('vimeo', 'vimeo'), ('other', 'iframe')], max_length=50)),
                ('source_id_string', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='static/sonovsite/son')),
                ('is_visible', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('short_desc', models.CharField(blank=True, max_length=72, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='son',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='video_tags', to='main.Tag'),
        ),
    ]
