# Generated by Django 2.0.3 on 2018-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='audio_file',
            field=models.FileField(default='', upload_to='static/main/audio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='son',
            name='thumbnail',
            field=models.ImageField(upload_to='static/main/thumbnail'),
        ),
    ]
