# Generated by Django 2.0.3 on 2018-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180330_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='static/main/audio'),
        ),
    ]
