# Generated by Django 2.0.3 on 2018-08-10 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_son_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='son',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='static/main/audio', verbose_name='Fichier son'),
        ),
        migrations.AlterField(
            model_name='son',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='A quelle date le rendre visible'),
        ),
        migrations.AlterField(
            model_name='son',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visible dès maintenant?'),
        ),
        migrations.AlterField(
            model_name='son',
            name='short_desc',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='Un petit mot facultatif'),
        ),
        migrations.AlterField(
            model_name='son',
            name='source_id_string',
            field=models.CharField(max_length=100, verbose_name='Caractères uniques du son'),
        ),
        migrations.AlterField(
            model_name='son',
            name='source_site',
            field=models.CharField(choices=[('youtube', 'youtube'), ('soundcloud', 'soundcloud'), ('vimeo', 'vimeo'), ('other', 'iframe')], max_length=50, verbose_name='Plateforme source'),
        ),
        migrations.AlterField(
            model_name='son',
            name='source_url',
            field=models.CharField(max_length=200, verbose_name='URL complète du son'),
        ),
        migrations.AlterField(
            model_name='son',
            name='thumbnail',
            field=models.ImageField(upload_to='static/main/img', verbose_name="Image d'aperçu"),
        ),
        migrations.AlterField(
            model_name='son',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre complet'),
        ),
    ]
