# Generated by Django 2.0.3 on 2018-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180810_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
