# Generated by Django 2.0.3 on 2018-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181106_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_private',
        ),
        migrations.AddField(
            model_name='son',
            name='is_for_be',
            field=models.BooleanField(default=False),
        ),
    ]
