# Generated by Django 2.0.3 on 2018-11-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181106_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
