# Generated by Django 2.0.3 on 2019-03-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181107_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonforbe',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='SonForBe',
        ),
    ]
