# Generated by Django 2.1.7 on 2019-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190309_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
