# Generated by Django 2.1.7 on 2019-10-19 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190617_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='A quelle date le rendre visible')),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
