# Generated by Django 2.1.7 on 2019-10-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191019_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='forum_user',
            field=models.BooleanField(default=False, verbose_name='Voulez vous être aussi inscrit au forum ?'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Votre nom ou pseudonyme'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Votre email'),
        ),
    ]
