# Generated by Django 2.1.7 on 2019-10-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191020_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Votre nom ou pseudonyme — facultatif'),
        ),
    ]
